kind: pipeline
name: drone
clone:
  disable: true
steps:
  - name: maven-install
    image: maven:3-jdk-10
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: code-scp
    image: appleboy/drone-scp
    settings:
      host: 121.36.56.213
      username: root
      password: Yp82253452
      port: 22
      target: /opt/projects/mass
      source: docker-compose.yml

  - name: code-deploy
    image: appleboy/drone-ssh
    settings:
      host: 121.36.56.213
      username: root
      password: Yp82253452
      port: 22
      script:
        - cd /opt/projects/mass
        - docker-compose pull
        - docker-compose up -d --force-recreate
volumes:
  - name: maven-cache
    host:
      path: /tmp/maven/cache
