kind: pipeline
name: mass-api


trigger:
  branch:
    - master
clone:
  skip_verify: true

steps:
  - name: maven-install
    image: maven:3-jdk-8
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: docker
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
      - name: certs
        path: /etc/ssl/certs
    settings:
      registry: 62.234.46.46:30738
      repo: 62.234.46.46:30738/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags:
        - ${DRONE_BUILD_NUMBER}
      build_args:
        - APPDIR=./target/app.jar
        - PORT=8080
deploy:
  rancher:
    image: pelotech/drone-rancher
    url: https://62.234.46.46:7002
    access_key: token-ckkjg
    secret_key: bgr7nnf62m49fptbpglqsnrc85m5snkpsscs4nj8hrmrww7kc8sdnt
    service: drone/drone
    docker_image: 62.234.46.46:30738/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
volumes:
  - name: certs
    host:
      path: /etc/ssl/certs
  - name: maven-cache
    host:
      path: /opt/cache/maven
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker


