kind: pipeline
name: mass-api

environment:
  DOMAIN: mass.zhihuizhan.net
  REGISTRY: registry.doatu.com
  PATHPREFIX: api
  PROFILE: prod
  APPDIR: ./target/app.jar
  PORT: 8080

trigger:
  branch:
    - master
clone:
  skip_verify: true

steps:

  - name: maven-install
    image: maven:3-jdk-8
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    volumes:
      - name: maven-cache
        path: /root/.m2
  - name: docker
    image: plugins/docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    settings:
      registry: registry.doatu.com
      repo: registry.doatu.com/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags:
        - ${DRONE_BUILD_NUMBER}

  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker build --rm=true -f Dockerfile -t $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} . --pull=true --build-arg APPDIR=$APPDIR --build-arg PORT=$PORT
      - docker push $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}

  - name: rancher
    image: pelotech/drone-rancher
    url: https://62.234.46.46:7002/v3
    access_key: token-ckkjg
    secret_key: bgr7nnf62m49fptbpglqsnrc85m5snkpsscs4nj8hrmrww7kc8sdnt
    service: ${DRONE_STAGE_NAME}
    docker_image: $REGISTRY/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}


volumes:
  - name: maven-cache
    host:
      path: /opt/cache/maven
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker


