kind: pipeline
name: mass-api

environment:
  DOMAIN: mass.zhihuizhan.net
  PATHPREFIX: api
  PROFILE: master
  APPDIR: ./target/app.jar
  PORT: 8080

steps:

  - name: maven-install
    image: maven:3-jdk-8
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true
    volumes:
      - name: maven-cache
        path: /root/.m2

  - name: build
    image: plugins/docker
    settings:
      mirror: https://hccwwfjl.mirror.aliyuncs.com/
      registry: swr.cn-north-1.myhuaweicloud.com
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}
      tags: ${DRONE_BUILD_NUMBER}
      build_args:
        - APPDIR
        - PORT

  - name: release
    image: docker:dind
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    commands:
      - docker service update --image swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER} ${DRONE_STAGE_NAME}-${DRONE_BRANCH}_service --with-registry-auth

  - name: release-failed
    image: docker:dind
    environment:
      IMAGE: swr.cn-north-1.myhuaweicloud.com/a82253452/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: registry-auth
        path: /root/.docker
    when:
      status:
        - failure
    commands:
      - docker stack deploy -c docker-compose.yml ${DRONE_STAGE_NAME}-${DRONE_BRANCH} --with-registry-auth

volumes:
  - name: maven-cache
    host:
      path: /opt/cache/maven
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: registry-auth
    host:
      path: /root/.docker

