# 示例
stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: 62.234.46.46:30738/maven
          shellScript: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: 62.234.46.46:30738/test:${CICD_EXECUTION_SEQUENCE}
          # （可选）是否推送到远端仓库
          pushRemote: true
          registry: 62.234.46.46:30738
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml
