version: "3"
networks:
  default:
    external:
      name: swarm-net
services:
  mass:
    container_name: mass
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/mass
    networks:
      - default-network
    labels:
      - traefik.http.routers.mass-http.rule=Host(`mass.zhihuizhan.net`)&& PathPrefix(`/api`)
      - traefik.http.middlewares.mass-http.redirectscheme.scheme=https_redirect

      - traefik.http.routers.mass.rule=Host(`mass.zhihuizhan.net`)&& PathPrefix(`/api`)
      - traefik.http.routers.mass.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.strip-prefix-api.stripprefix.prefixes=/api
      - traefik.http.routers.mass.middlewares=strip-prefix-api@docker
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /etc/localtime:/etc/localtime