version: "3"
networks:
  default:
    external:
      name: swarm-net
services:
  service:
    image: 192.168.0.2:5000/${DRONE_STAGE_NAME}/${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    deploy:
      deploy:
        replicas: 2
      labels:
        - traefik.enable=true

        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.rule=Host(`${DOMAIN}`)&& PathPrefix(`/${PATHPREFIX}`)
        - traefik.http.services.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.loadbalancer.server.port=${PORT}
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.middlewares=https_redirect

        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.rule=Host(`${DOMAIN}`)&& PathPrefix(`/${PATHPREFIX}`)
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.tls.certresolver=mytlschallenge

        - traefik.http.middlewares.strip-prefix-${PATHPREFIX}.stripprefix.prefixes=/${PATHPREFIX}
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.middlewares=strip-prefix-${PATHPREFIX}@docker
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.middlewares=strip-prefix-${PATHPREFIX}@docker
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      PORT: ${PORT}
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://192.168.0.2:12201"
    volumes:
      - /etc/localtime:/etc/localtime