version: "3"
networks:
  default:
    external:
      name: default-network
services:
  mass:
    container_name: mass
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/mass
    labels:
      - traefik.http.routers.mass.rule=Host(`mass.zhihuizhan.net`)
      - traefik.http.routers.mass.tls.certresolver=mytlschallenge
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - /etc/localtime:/etc/localtime