version: "3"
networks:
  default:
    external:
      name: swarm-net
services:
  service:
    image: ${IMAGE}
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
      labels:
        - finder.traefik.http=true

        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.rule=Host(`${DOMAIN}`)&& PathPrefix(`/${PATHPREFIX}`)
        - traefik.http.services.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.loadbalancer.server.port=${PORT}
        - traefik.http.middlewares.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.redirectscheme.scheme=https_redirect

        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.rule=Host(`${DOMAIN}`)&& PathPrefix(`/${PATHPREFIX}`)
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-https.tls.certresolver=mytlschallenge

        - traefik.http.middlewares.strip-prefix-${PATHPREFIX}.stripprefix.prefixes=/${PATHPREFIX}
        - traefik.http.routers.${DRONE_STAGE_NAME}-${DRONE_BRANCH}-http.middlewares=strip-prefix-${PATHPREFIX}@docker
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      PORT: ${PORT}
    volumes:
      - /etc/localtime:/etc/localtime