server:
  port: 8080
  tomcat:
    max-http-header-size: 10240000
spring:
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://121.36.56.213:3306/xxx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 10
      minIdle: 10
      maxActive: 2000
      maxWait: 60000
  redis:
    host: 121.36.56.213
    port: 6379
    database: 0
    password: zlsxsdfike.#@!
mybatis:
  type-aliases-package: com.f4w.entity
  #  mapper-locations: classpath:com/f4w/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
  wrapKeyword: '`{0}`'

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql;pageNum=pageNum;pageSize=pageSize;
jwt:
  key: 0e00568f23686b08abae11534a0ef1020e00568f23686b08abae11534a0ef102
  exp: 1