path:
  filesave: /data/package/
  filetemp: /data/temp/
xxl:
  job:
    admin:
      addresses: https://xxl.zhihuizhan.net/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      ip:
      port: 0
      logpath: /var/log/xxl-job/jobhandler/
      logretentiondays: -1
    accessToken:
