spring:
  datasource:
    druid:
      url: jdbc:mysql://121.36.56.213:3306/xxx?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useSSL=false
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 10
      minIdle: 10
      maxActive: 2000
      maxWait: 60000
  redis:
    host: 114.115.250.201
    port: 6379
    database: 0
    password: Yuping82253452
mybatis:
  type-aliases-package: com.f4w.entity
  #  mapper-locations: classpath:com/f4w/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
  wrapKeyword: '`{0}`'

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jwt:
  key: 0e00568f23686b08abae11534a0ef1020e00568f23686b08abae11534a0ef102
  exp: 2
path:
  filesave: D:/packzipfile/
  filetemp: D:/tmp/
weapp:
  open:
    componentAppId: wxcfd4c6237161d1e7
    componentSecret: 96c0b9554390e49d5bc0825314a5249a
    componentToken: token
    componentAesKey: r82FieYYZZ2tTG3Gklh9LBCh3k4Gxtwgsai4n2juvk1
server:
  port: 8081
xxl:
  job:
    admin:
      addresses: https://xxl.zhihuizhan.net/xxl-job-admin
    executor:
      appname: xxl123asd
      ip:
      port: 12356
      logpath: /var/log/xxl-job/jobhandler/
      logretentiondays: -1
    accessToken:
