path:
  filesave: D:/packzipfile/
  filetemp: D:/tmp/
xxl:
  job:
    admin:
      addresses: https://xxl.zhihuizhan.net/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample-dev
      ip:
      port: 0
      logpath: /var/log/xxl-job/jobhandler/
      logretentiondays: -1
    accessToken: